### ISSUE TITLE
can't start tozo app with psql (v 15.1).

### ISSUE THREAD

**Issue by JavaPantry** [pgjones/tozo#2]
can't start tozo app with psql (v 15.1).
Error message:
raise LifespanFailureError("startup", message["message"])
hypercorn.utils.LifespanFailureError: Lifespan failure in startup. 'permission denied for schema public'

According [Article](https://www.cybertec-postgresql.com/en/error-permission-denied-schema-public/) PostgreSQL v15 change permission rules

Had to downgrade PostgreSQL to v14.6 (server run succeed)

Any suggestion on how to modify migration (or model) files to run on PostgreSQL v 15.1?

**Comment by pgjones** [comment]
The book was written before Postgres 15, so I'll need to investigate this. I'd recommend staying on Postgres 14 for now.

**Comment by JavaPantry** [comment]
Sounds good! Thank you.

**Comment by bapowell** [comment]
To resolve this I added the following to the end of recreate_db(), in backend/src/backend/run.py :

```python
    call(  # nosec
        ["psql", "-U", "postgres", "-d", f"{db_url.path.removeprefix('/')}", "-c", f"GRANT ALL ON SCHEMA public TO {db_url.username}"],
    )

```

**Comment by pgjones** [comment]
Thank you.

**Comment by pgjones** [comment]
I've added this to the example code with 45a24681f955907a2437db151fa38e06857fe0c6
