### ISSUE TITLE
Tozo.dev won't load

### ISSUE THREAD

**Issue by w3bdesign** [pgjones/tozo#3]
Complains about the HTTPS certificate and "HTTP Strict Transport Security".

The error code seems to be `NET::ERR_CERT_DATE_INVALID`

**Comment by w3bdesign** [comment]
@pgjones

**Comment by pgjones** [comment]
The ssl certificate had expired. I've fixed by running `terraform apply`. I'm not sure how I missed the expiry reminder issues though.
