### ISSUE TITLE
Expired certificate on tozo.dev

### ISSUE THREAD

**Issue by AroundTheLines** [pgjones/tozo#4]
Looks like the website certificate expired. Firefox screenshot:

![image](https://github.com/pgjones/tozo/assets/9636627/0c07a74c-a3bd-4431-a4d5-1b10e51134f2)

**Comment by pgjones** [comment]
Sorry about that, I've renewed it now.

The certificate is valid for 90 days, so I need to remember to run `terraform apply` before the end of that period. Let's encrypt does send a reminder email, but I renewed the wrong certificate (my personal site pgjones.dev) instead.
