### ISSUE TITLE
https://tozo.dev - SSL certs have expired on november 8th

### ISSUE THREAD

**Issue by linuxd3v** [pgjones/tozo#5]
https://tozo.dev - SSL certs have expired on november 8th

**Comment by linuxd3v** [comment]
The way I do keep up on my letsencrypt certs:   
     
1) home server that has [dnsrobocert](https://bytepursuits.com/letsencrypt-ssl-certificates-generation-using-dnsrobocert) running (its just uses certbot under the hood) - which keeps generating certs for all my domains using DNS-01 challenge.    
    
2) Then there is a nightly cron that distributes certs to all the servers that need them.    

3) Then there is [uptime-kuma](https://github.com/louislam/uptime-kuma) checking site uptime, and also you can configure ssl expiration check (just click the checkbox)

**Comment by pgjones** [comment]
Thanks, I've updated.
